### ISSUE TITLE
Missing NameBasedCallGraph and SnippetMining in ql/quries

### ISSUE THREAD

**Issue by t1ger-0527** [githubnext/testpilot#3]
Hi! Thank you very much for open-sourcing this research!

I'm trying to run it on `--snippets both` and my CodeQL database and try to replicate the results. But I think it's missing `NameBasedCallGraph` and `SnippetMining` in `ql/quries`. Is this expected or am I missing something?

**Comment by max-schaefer** [comment]
Apologies, snippet mining is not supported at this point.
