### ISSUE TITLE
Request: Seeking Support for Testing TypeScript GraphQL API

### ISSUE THREAD

**Issue by akhilender-bongirwar** [githubnext/testpilot#8]
- I am seeking assistance with testing a TypeScript GraphQL API that interacts with MongoDB. Can you provide guidance, including relevant code samples and accompanying tests?
- Furthermore, I would like to inquire about the potential code coverage achievable through TestPilot for this type of testing (out of 100%).
- If support for this specific scenario is not presently available, could you provide an estimate of when it might be released?

**Comment by max-schaefer** [comment]
See answer to https://github.com/githubnext/testpilot/issues/7.
